[project]
name = "iris"
version = "0.1.0"
description = "Backend which does object classification and scene description + extrapolation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.27.2",
    "python-dotenv>=1.0.1",
    "websockets>=13.1",
]
